### ISSUE TITLE
Custom channel causes file not found

### ISSUE THREAD

**Issue by danielfrg** [conda/constructor#28]
When using a custom conda channel constructor gets confused about the filenames.

constructor file:

```
name: adam
version: 1.3.0

channels:
  - http://repo.continuum.io/pkgs/free/
  - https://conda.anaconda.org/t/XXXXX/anaconda-adam

specs:
  - python
  - adam
  ...
```

Generates:

```
platform: osx-64
Fetching package metadata .....
Solving package specifications: ..........

fetching: python-2.7.11-0.tar.bz2
fetching: anaconda-adam::adam-1.3.0-py27_0.tar.bz2
... 
fetching: zlib-1.2.8-3.tar.bz2
Traceback (most recent call last):
  File "/Users/danielfrg/anaconda/bin/constructor", line 6, in <module>
    sys.exit(main())
  File "/Users/danielfrg/anaconda/lib/python3.5/site-packages/constructor/main.py", line 146, in main
    verbose=opts.verbose)
  File "/Users/danielfrg/anaconda/lib/python3.5/site-packages/constructor/main.py", line 84, in main_build
    create(info)
  File "/Users/danielfrg/anaconda/lib/python3.5/site-packages/constructor/shar.py", line 97, in create
    t.add(join(info['_download_dir'], fn), 'pkgs/' + fn)
  File "/Users/danielfrg/anaconda/lib/python3.5/tarfile.py", line 1925, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/Users/danielfrg/anaconda/lib/python3.5/tarfile.py", line 1794, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/danielfrg/.conda/constructor/osx-64/anaconda-adam::adam-1.3.0-py27_0.tar.bz2'
```

```
cd /Users/danielfrg/.conda/constructor/osx-64/
➜  osx-64 ls
total 48808
-rw-r--r--  1 danielfrg  staff    80K 20 Jun 12:09 _license-1.1-py27_1.tar.bz2
-rw-r--r--  1 danielfrg  staff    83K 20 Jun 12:09 adam-1.3.0-py27_0.tar.bz2
...
```

Constructor downlaods the file as `adam-1.3.0-py27_0.tar.bz2` but then tries to use `anaconda-adam::adam-1.3.0-py27_0.tar.bz2`.

**Comment by loriab** [comment]
Same problem, I believe, whereby custom channel request

```
packages:
  - http://conda.anaconda.org/menpo/osx-64/boost-1.59.0-py27_0.tar.bz2
```

leads to

```
Error: no package 'boost-1.59.0-py27_0.tar.bz2' in http://conda.anaconda.org/menpo/osx-64/
```

For `conda-build` and `constructor` held constant at `1.21.0` and `1.2.0`, respectively, the problem is seen at `conda` `4.1.2` and `4.1.0` but fixed by the downgrade below.

```
    conda:     4.1.0-py27_0 defaults --> 4.0.9-py27_0 defaults
    conda-env: 2.5.1-py27_0 defaults --> 2.4.5-py27_0 defaults
```

**Comment by danielfrg** [comment]
cc @kalefranz could you help us verify that this is a conda issue and not constructor?

**Comment by bkreider** [comment]
I'm pretty certain this is a constructor issue as it also hits cas-installer.  The filename component needs to split off the "channel::" portion of the string when saving to the cache, retrieving from the cache, and when building the tarball.

**Comment by mcg1969** [comment]
What version of constructor are you using?

**Comment by mcg1969** [comment]
I'm pretty sure we fixed this in master

**Comment by danielfrg** [comment]
I am using constructor `1.2.0`.

**Comment by loriab** [comment]
Issue still exists for me with constructor `1.2.0` and conda `4.1.3`

**Comment by loriab** [comment]
With constructor update to `1.2.1`, issue still exists with new error message. conda `4.1.3`, conda-build `1.21.2`, conda-env `2.5.1`

```
platform: linux-64
Fetching package metadata .....Traceback (most recent call last):
  File "/shortened/miniconda11/bin/constructor", line 6, in <module>
    sys.exit(main())
  File "/shortened/miniconda11/lib/python2.7/site-packages/constructor/main.py", line 146, in main
    verbose=opts.verbose)
  File "/shortened/miniconda11/lib/python2.7/site-packages/constructor/main.py", line 81, in main_build
    fcp.main(info, verbose=verbose)
  File "/shortened/miniconda11/lib/python2.7/site-packages/constructor/fcp.py", line 168, in main
    index = get_index(urls, prepend=False, platform=info['_platform'])
  File "/shortened/miniconda11/lib/python2.7/site-packages/conda/api.py", line 26, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/shortened/miniconda11/lib/python2.7/site-packages/conda/fetch.py", line 286, in fetch_index
    for url in iterkeys(channel_urls)]
  File "/shortened/miniconda11/lib/python2.7/site-packages/conda/fetch.py", line 67, in func
    res = f(*args, **kwargs)
  File "/shortened/miniconda11/lib/python2.7/site-packages/conda/fetch.py", line 159, in fetch_repodata
    raise RuntimeError(msg)
RuntimeError: Could not find anaconda.org user conda-forge
```

**Comment by ilanschnell** [comment]
Fixed in 1.3.0
